export type OrderStatus = 'Auto-Generated by Bot' | 'Confirmed' | 'Pending' | 'Delivered' | 'Cancelled';

export interface OrderItem {
  sku: string;
  productName: string;
  quantity: number;
  unitPrice: number;
}

export interface Order {
  id: string; // e.g., "ORD-8821"
  customerName: string;
  phoneNumber: string;
  deliveryAddress: string;
  items: OrderItem[];
  totalAmount: number; // in BDT
  currency: string;
  orderDate: string; // e.g., "2026-08-02 14:30"
  status: OrderStatus;
  conversationId?: string;
  channel: 'WhatsApp' | 'Messenger' | 'Instagram' | 'Website';
}
