import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Order } from '@/types/orders';
import Table, { Column } from '@/components/ui/Table';
import Badge from '@/components/ui/Badge';
import Input from '@/components/ui/Input';
import { 
  Search, 
  MessageSquare, 
  Phone, 
  MapPin, 
  Filter, 
  Calendar
} from 'lucide-react';

// Realistic Mock Orders Auto-Generated by Canvas AI Customer Service Chatbot
const MOCK_ORDERS: Order[] = [
  {
    id: 'ORD-9401',
    customerName: 'Tanvir Ahmed',
    phoneNumber: '+8801711223344',
    deliveryAddress: 'House 42, Road 11, Block D, Banani, Dhaka',
    items: [{ sku: 'CNV-ACR-500', productName: 'Canvas Heavy Body Acrylic Paint Set (12 x 75ml)', quantity: 1, unitPrice: 1450 }],
    totalAmount: 1450, currency: 'BDT', orderDate: '2026-08-02 10:45 AM',
    status: 'Auto-Generated by Bot', channel: 'WhatsApp', conversationId: 'conv-101',
  },
  {
    id: 'ORD-9402',
    customerName: 'Ayesha Rahman',
    phoneNumber: '+8801899887766',
    deliveryAddress: 'Flat 4B, Green Road, Dhanmondi, Dhaka',
    items: [{ sku: 'CNV-BRS-SYN6', productName: 'Canvas Masterstroke Synthetic Sable Brush Set (6 Pcs)', quantity: 2, unitPrice: 890 }],
    totalAmount: 1780, currency: 'BDT', orderDate: '2026-08-02 09:30 AM',
    status: 'Confirmed', channel: 'Instagram', conversationId: 'conv-104',
  },
  {
    id: 'ORD-9403',
    customerName: 'Sajid Hossain',
    phoneNumber: '+8801655443322',
    deliveryAddress: 'Holding 12, CDA Avenue, Nasirabad, Chattogram',
    items: [
      { sku: 'CNV-BRS-HOG8', productName: 'Canvas Imperial Hog Bristle Brush Set (5 Pcs)', quantity: 1, unitPrice: 1150 },
      { sku: 'CNV-CAN-1216', productName: 'Canvas Stretched Cotton Canvas 12x16 (Pack of 2)', quantity: 2, unitPrice: 750 },
    ],
    totalAmount: 2650, currency: 'BDT', orderDate: '2026-08-01 04:15 PM',
    status: 'Auto-Generated by Bot', channel: 'WhatsApp', conversationId: 'conv-103',
  },
  {
    id: 'ORD-9404',
    customerName: 'Nusrat Jahan',
    phoneNumber: '+8801522114433',
    deliveryAddress: 'Studio 3, Art Institute Campus, Mirpur 10, Dhaka',
    items: [{ sku: 'CNV-WTR-24P', productName: 'Canvas Artists Water Colour Pan Set (24 Half Pans)', quantity: 10, unitPrice: 2200 }],
    totalAmount: 22000, currency: 'BDT', orderDate: '2026-08-01 02:00 PM',
    status: 'Pending', channel: 'Messenger', conversationId: 'conv-102',
  },
  {
    id: 'ORD-9405',
    customerName: 'Mahmudul Hasan',
    phoneNumber: '+8801911335577',
    deliveryAddress: 'House 15, Sector 7, Uttara, Dhaka',
    items: [{ sku: 'CNV-OIL-PRO6', productName: 'Canvas Classic Oil Colour Starter Set (6 x 37ml)', quantity: 1, unitPrice: 1850 }],
    totalAmount: 1850, currency: 'BDT', orderDate: '2026-07-31 06:50 PM',
    status: 'Delivered', channel: 'Website',
  },
];

export const OrdersPage: React.FC = () => {
  const navigate = useNavigate();
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedStatus, setSelectedStatus] = useState<string>('All');

  const filteredOrders = MOCK_ORDERS.filter((order) => {
    const matchesSearch =
      order.id.toLowerCase().includes(searchQuery.toLowerCase()) ||
      order.customerName.toLowerCase().includes(searchQuery.toLowerCase()) ||
      order.phoneNumber.includes(searchQuery) ||
      order.deliveryAddress.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesStatus = selectedStatus === 'All' || order.status === selectedStatus;
    return matchesSearch && matchesStatus;
  });

  const getStatusBadge = (status: Order['status']) => {
    switch (status) {
      case 'Auto-Generated by Bot': return <Badge variant="indigo" size="sm" dot>Auto-Generated by Bot</Badge>;
      case 'Confirmed': return <Badge variant="success" size="sm" dot>Confirmed</Badge>;
      case 'Pending': return <Badge variant="warning" size="sm" dot>Pending Review</Badge>;
      case 'Delivered': return <Badge variant="info" size="sm">Delivered</Badge>;
      default: return <Badge variant="neutral" size="sm">{status}</Badge>;
    }
  };

  const columns: Column<Order>[] = [
    {
      header: 'Order Reference',
      cell: (order) => (
        <div className="space-y-0.5">
          <span className="font-mono text-xs font-bold text-indigo-500 dark:text-indigo-400 block">{order.id}</span>
          <span className="text-[11px] text-slate-500 flex items-center gap-1 font-mono">
            <Calendar className="w-3 h-3" />
            {order.orderDate}
          </span>
        </div>
      ),
    },
    {
      header: 'Customer Details',
      cell: (order) => (
        <div className="space-y-1 py-1 max-w-xs">
          <div className="flex items-center gap-2">
            <span className="font-semibold text-slate-900 dark:text-slate-100 text-sm">{order.customerName}</span>
            <span className="text-[10px] font-mono bg-slate-200 dark:bg-slate-800 text-slate-600 dark:text-slate-400 px-1.5 py-0.5 rounded">
              {order.channel}
            </span>
          </div>
          <div className="flex items-center gap-1.5 text-xs text-slate-500">
            <Phone className="w-3 h-3 text-indigo-500 shrink-0" />
            <span className="font-mono">{order.phoneNumber}</span>
          </div>
          <div className="flex items-start gap-1.5 text-xs text-slate-500">
            <MapPin className="w-3 h-3 shrink-0 mt-0.5" />
            <span className="line-clamp-1" title={order.deliveryAddress}>{order.deliveryAddress}</span>
          </div>
        </div>
      ),
    },
    {
      header: 'Ordered Products',
      cell: (order) => (
        <div className="space-y-1">
          {order.items.map((item, idx) => (
            <div key={idx} className="text-xs">
              <span className="font-medium text-slate-800 dark:text-slate-300">{item.productName}</span>{' '}
              <span className="font-mono text-indigo-500 dark:text-indigo-400">x{item.quantity}</span>
            </div>
          ))}
        </div>
      ),
    },
    {
      header: 'Total Price',
      cell: (order) => (
        <div className="font-bold text-emerald-600 dark:text-emerald-400 text-sm">
          ৳{order.totalAmount.toLocaleString()} BDT
        </div>
      ),
    },
    {
      header: 'Order Status',
      cell: (order) => getStatusBadge(order.status),
    },
    {
      header: 'Chat Context',
      cell: () => (
        <button
          onClick={() => navigate('/chat')}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-slate-100 dark:bg-slate-900 hover:bg-slate-200 dark:hover:bg-slate-800 border border-slate-300 dark:border-slate-700 hover:border-indigo-400/60 rounded-lg text-xs font-medium text-slate-700 dark:text-slate-200 hover:text-indigo-600 dark:hover:text-indigo-300 transition-all cursor-pointer shadow-sm"
          title="View full conversation transcript"
        >
          <MessageSquare className="w-3.5 h-3.5 text-indigo-500" />
          <span>View Chat History</span>
        </button>
      ),
    },
  ];

  return (
    <div className="space-y-6">
      {/* Header Section */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-xl font-bold text-slate-900 dark:text-slate-100 tracking-tight">Auto-Generated Orders</h1>
            <Badge variant="indigo" size="sm" dot>AI Bot Synced</Badge>
          </div>
          <p className="text-xs text-slate-500 mt-1">
            Orders captured automatically from customer chats when name, phone, and address are provided
          </p>
        </div>

        {/* Overview Stats */}
        <div className="flex items-center gap-3 bg-slate-100 dark:bg-slate-900/60 border border-slate-200 dark:border-slate-800 p-2.5 rounded-xl text-xs font-mono">
          <div className="px-3 border-r border-slate-300 dark:border-slate-800">
            <span className="text-slate-500 block text-[10px]">TOTAL ORDERS</span>
            <span className="font-bold text-slate-800 dark:text-slate-200 text-sm">{MOCK_ORDERS.length}</span>
          </div>
          <div className="px-3">
            <span className="text-slate-500 block text-[10px]">BOT GENERATED</span>
            <span className="font-bold text-indigo-600 dark:text-indigo-400 text-sm">
              {MOCK_ORDERS.filter((o) => o.status === 'Auto-Generated by Bot').length}
            </span>
          </div>
        </div>
      </div>

      {/* Filter and Search Toolbar */}
      <div className="flex flex-col sm:flex-row items-center justify-between gap-3 bg-slate-100 dark:bg-slate-900/40 p-3 border border-slate-200 dark:border-slate-800 rounded-xl">
        <div className="w-full sm:w-80">
          <Input
            placeholder="Search Order ID, name, phone, address..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            leftIcon={<Search className="w-3.5 h-3.5 text-slate-400" />}
          />
        </div>

        <div className="flex items-center gap-2 w-full sm:w-auto overflow-x-auto pb-1 sm:pb-0">
          <span className="text-xs text-slate-500 flex items-center gap-1 shrink-0">
            <Filter className="w-3.5 h-3.5" /> Filter Status:
          </span>
          {['All', 'Auto-Generated by Bot', 'Confirmed', 'Pending', 'Delivered'].map((status) => (
            <button
              key={status}
              onClick={() => setSelectedStatus(status)}
              className={`px-2.5 py-1 rounded-lg text-xs font-medium transition-colors whitespace-nowrap cursor-pointer ${
                selectedStatus === status
                  ? 'bg-indigo-600 text-white'
                  : 'bg-slate-200 dark:bg-slate-800/60 text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200'
              }`}
            >
              {status}
            </button>
          ))}
        </div>
      </div>

      {/* Data Table */}
      <Table columns={columns} data={filteredOrders} keyExtractor={(order) => order.id} />
    </div>
  );
};

export default OrdersPage;
